version: '2'

services:
  proxy:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '10'
    ports:
      - 8000:80
  db:
    command: -c 'shared_buffers=2048MB' -c 'effective_cache_size=4096'
  web:
    command: --db_host=db -r odoo -w odoo
