version: '2'
services:
  pgadmin:
    image: dpage/pgadmin4:3
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 8070:80

